-- 0000_baseline.sql
-- Full current schema of the public schema, generated by introspecting
-- the live Supabase database. Fully idempotent (safe to run against the
-- existing production DB, where every statement is a no-op, or against a
-- fresh Supabase project to recreate the schema from empty).
--
-- Authorization is enforced in the app layer (no RLS). The cross-schema FK
-- from user_profiles.id -> auth.users(id) requires Supabase's auth schema
-- to exist (it does on any Supabase project).

-- ============ Tables ============
CREATE TABLE IF NOT EXISTS ad_creatives (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  campaign_id text NOT NULL,
  platform text NOT NULL,
  ad_id text NOT NULL,
  ad_name text NOT NULL,
  creative_type text NOT NULL,
  headline text NOT NULL,
  body_copy text NOT NULL,
  thumbnail_url text NOT NULL,
  impressions bigint DEFAULT 0 NOT NULL,
  clicks bigint DEFAULT 0 NOT NULL,
  spend numeric(12,2) DEFAULT 0 NOT NULL,
  conversions bigint DEFAULT 0 NOT NULL,
  ctr numeric(8,4) DEFAULT 0 NOT NULL,
  cpc numeric(10,4) DEFAULT 0 NOT NULL,
  cpa numeric(10,2) DEFAULT 0 NOT NULL,
  first_served date NOT NULL,
  last_served date NOT NULL,
  days_running integer DEFAULT 0 NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS alert_history (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  rule_id uuid NOT NULL,
  client_id uuid NOT NULL,
  triggered_at timestamp with time zone DEFAULT now() NOT NULL,
  metric text NOT NULL,
  actual_value numeric NOT NULL,
  threshold_value numeric NOT NULL,
  severity text DEFAULT 'warning'::text NOT NULL,
  status text DEFAULT 'triggered'::text NOT NULL,
  resolved_at timestamp with time zone,
  notification_sent boolean DEFAULT true NOT NULL,
  rule_name text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS alert_rules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  name text NOT NULL,
  metric text NOT NULL,
  condition text NOT NULL,
  threshold numeric NOT NULL,
  evaluation_window text DEFAULT 'daily'::text NOT NULL,
  platform text,
  campaign_id text,
  enabled boolean DEFAULT true NOT NULL,
  recipients text[] DEFAULT '{}'::text[] NOT NULL,
  frequency text DEFAULT 'realtime'::text NOT NULL,
  severity text DEFAULT 'warning'::text NOT NULL,
  quiet_hours_enabled boolean DEFAULT false NOT NULL,
  quiet_hours_start text,
  quiet_hours_end text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS attribution_journeys (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  conversion_date date NOT NULL,
  revenue numeric(12,2) DEFAULT 0 NOT NULL,
  path text[] DEFAULT '{}'::text[] NOT NULL,
  converting_platform text NOT NULL,
  touch_count integer DEFAULT 1 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS campaign_budgets (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  campaign_id text NOT NULL,
  monthly_budget numeric(12,2) NOT NULL,
  month text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS campaign_performance (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  platform text NOT NULL,
  campaign_id text NOT NULL,
  campaign_name text NOT NULL,
  date date NOT NULL,
  impressions integer DEFAULT 0 NOT NULL,
  clicks integer DEFAULT 0 NOT NULL,
  spend numeric(12,2) DEFAULT 0 NOT NULL,
  conversions integer DEFAULT 0 NOT NULL,
  ctr numeric(8,4) DEFAULT 0 NOT NULL,
  cpc numeric(10,4) DEFAULT 0 NOT NULL,
  cpm numeric(10,4) DEFAULT 0 NOT NULL,
  raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  revenue numeric(14,2) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  session_id uuid NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  reference_context jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_sessions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  title text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS client_members (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  client_id uuid NOT NULL,
  role text DEFAULT 'viewer'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  industry text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_cohorts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  acquisition_platform text NOT NULL,
  cohort_month text NOT NULL,
  customers integer DEFAULT 0 NOT NULL,
  acquisition_spend numeric(14,2) DEFAULT 0 NOT NULL,
  retention jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS dashboards (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  name text DEFAULT 'Default'::text NOT NULL,
  is_default boolean DEFAULT true NOT NULL,
  layouts jsonb DEFAULT '{"lg": [], "md": [], "sm": []}'::jsonb NOT NULL,
  widgets jsonb DEFAULT '[]'::jsonb NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS report_schedules (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  name text NOT NULL,
  frequency text NOT NULL,
  day_of_week integer,
  day_of_month integer,
  time_of_day text DEFAULT '09:00'::text NOT NULL,
  date_range_type text DEFAULT 'last_30'::text NOT NULL,
  custom_days integer,
  include_comparison boolean DEFAULT true NOT NULL,
  recipients text[] DEFAULT '{}'::text[] NOT NULL,
  subject_template text DEFAULT '{{clientName}} Performance Report'::text NOT NULL,
  message_template text DEFAULT ''::text NOT NULL,
  require_approval boolean DEFAULT false NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  last_sent_at timestamp with time zone,
  next_send_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS reports (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  client_id uuid NOT NULL,
  title text NOT NULL,
  date_range_start date NOT NULL,
  date_range_end date NOT NULL,
  comparison_start date NOT NULL,
  comparison_end date NOT NULL,
  narrative text DEFAULT ''::text NOT NULL,
  metrics_summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  share_token text,
  share_password_hash text,
  share_expires_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid NOT NULL,
  full_name text,
  role text DEFAULT 'client_user'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- ============ Primary keys, unique & check constraints ============
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ad_creatives_creative_type_check' AND conrelid = 'public.ad_creatives'::regclass
  ) THEN
    ALTER TABLE ad_creatives ADD CONSTRAINT ad_creatives_creative_type_check CHECK (creative_type = ANY (ARRAY['image'::text, 'video'::text, 'carousel'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ad_creatives_platform_check' AND conrelid = 'public.ad_creatives'::regclass
  ) THEN
    ALTER TABLE ad_creatives ADD CONSTRAINT ad_creatives_platform_check CHECK (platform = ANY (ARRAY['google'::text, 'meta'::text, 'tiktok'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ad_creatives_status_check' AND conrelid = 'public.ad_creatives'::regclass
  ) THEN
    ALTER TABLE ad_creatives ADD CONSTRAINT ad_creatives_status_check CHECK (status = ANY (ARRAY['active'::text, 'fatigued'::text, 'paused'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ad_creatives_pkey' AND conrelid = 'public.ad_creatives'::regclass
  ) THEN
    ALTER TABLE ad_creatives ADD CONSTRAINT ad_creatives_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_history_severity_check' AND conrelid = 'public.alert_history'::regclass
  ) THEN
    ALTER TABLE alert_history ADD CONSTRAINT alert_history_severity_check CHECK (severity = ANY (ARRAY['critical'::text, 'warning'::text, 'info'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_history_status_check' AND conrelid = 'public.alert_history'::regclass
  ) THEN
    ALTER TABLE alert_history ADD CONSTRAINT alert_history_status_check CHECK (status = ANY (ARRAY['triggered'::text, 'acknowledged'::text, 'resolved'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_history_pkey' AND conrelid = 'public.alert_history'::regclass
  ) THEN
    ALTER TABLE alert_history ADD CONSTRAINT alert_history_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_condition_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_condition_check CHECK (condition = ANY (ARRAY['above'::text, 'below'::text, 'increases_by_pct'::text, 'decreases_by_pct'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_evaluation_window_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_evaluation_window_check CHECK (evaluation_window = ANY (ARRAY['daily'::text, 'weekly'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_frequency_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_frequency_check CHECK (frequency = ANY (ARRAY['realtime'::text, 'hourly_digest'::text, 'daily_digest'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_metric_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_metric_check CHECK (metric = ANY (ARRAY['spend'::text, 'cpa'::text, 'ctr'::text, 'cpc'::text, 'conversions'::text, 'impressions'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_platform_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_platform_check CHECK (platform = ANY (ARRAY['google'::text, 'meta'::text, 'tiktok'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_severity_check' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_severity_check CHECK (severity = ANY (ARRAY['critical'::text, 'warning'::text, 'info'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_pkey' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attribution_journeys_converting_platform_check' AND conrelid = 'public.attribution_journeys'::regclass
  ) THEN
    ALTER TABLE attribution_journeys ADD CONSTRAINT attribution_journeys_converting_platform_check CHECK (converting_platform = ANY (ARRAY['google'::text, 'meta'::text, 'tiktok'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attribution_journeys_pkey' AND conrelid = 'public.attribution_journeys'::regclass
  ) THEN
    ALTER TABLE attribution_journeys ADD CONSTRAINT attribution_journeys_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaign_budgets_pkey' AND conrelid = 'public.campaign_budgets'::regclass
  ) THEN
    ALTER TABLE campaign_budgets ADD CONSTRAINT campaign_budgets_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaign_performance_platform_check' AND conrelid = 'public.campaign_performance'::regclass
  ) THEN
    ALTER TABLE campaign_performance ADD CONSTRAINT campaign_performance_platform_check CHECK (platform = ANY (ARRAY['google'::text, 'meta'::text, 'tiktok'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaign_performance_pkey' AND conrelid = 'public.campaign_performance'::regclass
  ) THEN
    ALTER TABLE campaign_performance ADD CONSTRAINT campaign_performance_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chat_messages_role_check' AND conrelid = 'public.chat_messages'::regclass
  ) THEN
    ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_role_check CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chat_messages_pkey' AND conrelid = 'public.chat_messages'::regclass
  ) THEN
    ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chat_sessions_pkey' AND conrelid = 'public.chat_sessions'::regclass
  ) THEN
    ALTER TABLE chat_sessions ADD CONSTRAINT chat_sessions_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_members_role_check' AND conrelid = 'public.client_members'::regclass
  ) THEN
    ALTER TABLE client_members ADD CONSTRAINT client_members_role_check CHECK (role = ANY (ARRAY['viewer'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_members_pkey' AND conrelid = 'public.client_members'::regclass
  ) THEN
    ALTER TABLE client_members ADD CONSTRAINT client_members_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'clients_pkey' AND conrelid = 'public.clients'::regclass
  ) THEN
    ALTER TABLE clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_cohorts_acquisition_platform_check' AND conrelid = 'public.customer_cohorts'::regclass
  ) THEN
    ALTER TABLE customer_cohorts ADD CONSTRAINT customer_cohorts_acquisition_platform_check CHECK (acquisition_platform = ANY (ARRAY['google'::text, 'meta'::text, 'tiktok'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_cohorts_pkey' AND conrelid = 'public.customer_cohorts'::regclass
  ) THEN
    ALTER TABLE customer_cohorts ADD CONSTRAINT customer_cohorts_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'dashboards_pkey' AND conrelid = 'public.dashboards'::regclass
  ) THEN
    ALTER TABLE dashboards ADD CONSTRAINT dashboards_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_date_range_type_check' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_date_range_type_check CHECK (date_range_type = ANY (ARRAY['last_7'::text, 'last_14'::text, 'last_30'::text, 'last_month'::text, 'last_quarter'::text, 'month_to_date'::text, 'custom'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_day_of_month_check' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_day_of_month_check CHECK (day_of_month >= 1 AND day_of_month <= 31);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_day_of_week_check' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_frequency_check' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_frequency_check CHECK (frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text, 'quarterly'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_pkey' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reports_pkey' AND conrelid = 'public.reports'::regclass
  ) THEN
    ALTER TABLE reports ADD CONSTRAINT reports_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'user_profiles_role_check' AND conrelid = 'public.user_profiles'::regclass
  ) THEN
    ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_role_check CHECK (role = ANY (ARRAY['agency_admin'::text, 'agency_member'::text, 'client_user'::text]));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'user_profiles_pkey' AND conrelid = 'public.user_profiles'::regclass
  ) THEN
    ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- ============ Foreign keys ============
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ad_creatives_client_id_fkey' AND conrelid = 'public.ad_creatives'::regclass
  ) THEN
    ALTER TABLE ad_creatives ADD CONSTRAINT ad_creatives_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_history_client_id_fkey' AND conrelid = 'public.alert_history'::regclass
  ) THEN
    ALTER TABLE alert_history ADD CONSTRAINT alert_history_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_history_rule_id_fkey' AND conrelid = 'public.alert_history'::regclass
  ) THEN
    ALTER TABLE alert_history ADD CONSTRAINT alert_history_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES alert_rules(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'alert_rules_client_id_fkey' AND conrelid = 'public.alert_rules'::regclass
  ) THEN
    ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'attribution_journeys_client_id_fkey' AND conrelid = 'public.attribution_journeys'::regclass
  ) THEN
    ALTER TABLE attribution_journeys ADD CONSTRAINT attribution_journeys_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaign_budgets_client_id_fkey' AND conrelid = 'public.campaign_budgets'::regclass
  ) THEN
    ALTER TABLE campaign_budgets ADD CONSTRAINT campaign_budgets_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaign_performance_client_id_fkey' AND conrelid = 'public.campaign_performance'::regclass
  ) THEN
    ALTER TABLE campaign_performance ADD CONSTRAINT campaign_performance_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chat_messages_session_id_fkey' AND conrelid = 'public.chat_messages'::regclass
  ) THEN
    ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'chat_sessions_client_id_fkey' AND conrelid = 'public.chat_sessions'::regclass
  ) THEN
    ALTER TABLE chat_sessions ADD CONSTRAINT chat_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_members_client_id_fkey' AND conrelid = 'public.client_members'::regclass
  ) THEN
    ALTER TABLE client_members ADD CONSTRAINT client_members_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'client_members_user_id_fkey' AND conrelid = 'public.client_members'::regclass
  ) THEN
    ALTER TABLE client_members ADD CONSTRAINT client_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'customer_cohorts_client_id_fkey' AND conrelid = 'public.customer_cohorts'::regclass
  ) THEN
    ALTER TABLE customer_cohorts ADD CONSTRAINT customer_cohorts_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'dashboards_client_id_fkey' AND conrelid = 'public.dashboards'::regclass
  ) THEN
    ALTER TABLE dashboards ADD CONSTRAINT dashboards_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'report_schedules_client_id_fkey' AND conrelid = 'public.report_schedules'::regclass
  ) THEN
    ALTER TABLE report_schedules ADD CONSTRAINT report_schedules_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reports_client_id_fkey' AND conrelid = 'public.reports'::regclass
  ) THEN
    ALTER TABLE reports ADD CONSTRAINT reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'user_profiles_id_fkey' AND conrelid = 'public.user_profiles'::regclass
  ) THEN
    ALTER TABLE user_profiles ADD CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ============ Indexes ============
CREATE INDEX IF NOT EXISTS idx_ad_creatives_client_campaign ON public.ad_creatives USING btree (client_id, campaign_id);

CREATE INDEX IF NOT EXISTS idx_ad_creatives_client_platform ON public.ad_creatives USING btree (client_id, platform);

CREATE INDEX IF NOT EXISTS idx_ad_creatives_client_status ON public.ad_creatives USING btree (client_id, status);

CREATE INDEX IF NOT EXISTS idx_alert_history_client ON public.alert_history USING btree (client_id);

CREATE INDEX IF NOT EXISTS idx_alert_history_rule ON public.alert_history USING btree (rule_id);

CREATE INDEX IF NOT EXISTS idx_alert_rules_client ON public.alert_rules USING btree (client_id);

CREATE INDEX IF NOT EXISTS attribution_journeys_client_date_idx ON public.attribution_journeys USING btree (client_id, conversion_date);

CREATE INDEX IF NOT EXISTS idx_campaign_budgets_client_month ON public.campaign_budgets USING btree (client_id, month);

CREATE INDEX IF NOT EXISTS idx_campaign_perf_campaign ON public.campaign_performance USING btree (campaign_id);

CREATE INDEX IF NOT EXISTS idx_campaign_perf_client_date ON public.campaign_performance USING btree (client_id, date);

CREATE INDEX IF NOT EXISTS idx_campaign_perf_platform ON public.campaign_performance USING btree (platform);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON public.chat_messages USING btree (session_id);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_client ON public.chat_sessions USING btree (client_id);

CREATE INDEX IF NOT EXISTS client_members_client_idx ON public.client_members USING btree (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS client_members_user_client_idx ON public.client_members USING btree (user_id, client_id);

CREATE INDEX IF NOT EXISTS customer_cohorts_client_idx ON public.customer_cohorts USING btree (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS dashboards_client_name_idx ON public.dashboards USING btree (client_id, name);

CREATE INDEX IF NOT EXISTS idx_report_schedules_client ON public.report_schedules USING btree (client_id);

CREATE INDEX IF NOT EXISTS idx_reports_client ON public.reports USING btree (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reports_share_token ON public.reports USING btree (share_token) WHERE (share_token IS NOT NULL);
